new4

diff --git a/.github/workflows/new.yml b/.github/workflows/new.yml
--- a/.github/workflows/new.yml
+++ b/.github/workflows/new.yml
@@ -39,52 +39,69 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Download Artifacts from GitHub Packages
+        run: |
+            mkdir -p downloaded_artifacts
+            echo "Downloading JAR files"
+            for jar in target/*.jar; do
+            [ -e "$jar" ] || continue
+            filename=$(basename $jar)
+            url="https://maven.pkg.github.com/${{ github.repository }}/$filename"
+            echo "Downloading $filename from $url"
+            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o downloaded_artifacts/$filename "$url"
+            if [ $? -eq 0 ]; then
+            echo "Downloaded $filename successfully"
+            else
+            echo "Failed to download $filename"
+            fi
+            done
+            echo "Downloading POM file"
+            pom_filename="${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom"
+            pom_url="https://maven.pkg.github.com/${{ github.repository }}/$pom_filename"
+            echo "Downloading $pom_filename from $pom_url"
+            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o downloaded_artifacts/$pom_filename "$pom_url"
+            if [ $? -eq 0 ]; then
+            echo "Downloaded $pom_filename successfully"
+            else
+            echo "Failed to download $pom_filename"
+            fi
+
+      - name: GitHub Attestation for JAR files
+        uses: actions/attest-build-provenance@v2
+        with:
+          subject-path: "downloaded_artifacts/*.jar"
+
+      - name: GitHub Attestation for POM file
+        uses: actions/attest-build-provenance@v2
+        with:
+          subject-path: "downloaded_artifacts/*.pom"
+          subject-name: "${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom"
+
       - name: Publish Java Artifacts to GitHub Release
         run: |
           cp pom.xml ${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom
           gh release upload ${{github.event.release.tag_name}} "${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom"
-          for jar in target/*.jar; do
+          for jar in downloaded_artifacts/*.jar; do
             [ -e "$jar" ] || continue
             gh release upload ${{github.event.release.tag_name}} "$jar"
           done
         env:
           GITHUB_TOKEN: ${{ github.TOKEN }}
 
-      - name: GitHub Attestation for JAR files
-        uses: actions/attest-build-provenance@v2
-        with:
-          subject-path: "target/*.jar"
+      # list files in downloaded_artifacts directory
+      - name: List downloaded artifacts
+        run: ls -l downloaded_artifacts
 
-      - name: GitHub Attestation for POM file
-        uses: actions/attest-build-provenance@v2
-        with:
-          subject-path: "pom.xml"
-          subject-name: "${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom"
-
-      - name: Download Artifacts from GitHub Packages
-        run: |
-          mkdir -p downloaded_artifacts
-          echo "Downloading JAR files"
-          for jar in target/*.jar; do
-            [ -e "$jar" ] || continue
-            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o downloaded_artifacts/$(basename $jar) "https://maven.pkg.github.com/${{ github.repository }}/$(basename $jar)"
-          done
-          echo "Downloading POM file"
-          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o downloaded_artifacts/${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom "https://maven.pkg.github.com/${{ github.repository }}/${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom"
-
-      - name: Verify downloaded artifacts with GitHub Attestation
+      - name: Verify build artifact with GitHub Attestation
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           for jar in downloaded_artifacts/*.jar; do
             [ -e "$jar" ] || continue
-            echo "Verifying $jar"
-            result=$(gh attestation verify $jar --repo "${{ github.repository }}")
-            echo "$result"
+            echo "Verifying ${jar}"
+            script -q -c "gh attestation verify "${jar}" --repo ${{ github.repository }}"
           done
-          echo "Verifying POM file"
-          result=$(gh attestation verify "downloaded_artifacts/${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom" --repo "${{ github.repository }}")
-          echo "$result"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          script -q -c "gh attestation verify "downloaded_artifacts/${{ steps.maven_artifact.outputs.artifactId }}-${{ steps.maven_artifact.outputs.version }}.pom" --repo ${{ github.repository }}"
 
       - name: Fail workflow if artifact is invalid
         env:
@@ -110,4 +127,4 @@ jobs:
             exit 1
           else
             echo "All verifications passed"
-          fi
+
